runtime:
  cache_dir: ./.cache/antora

site:
  title: Cloudnative Learning 101
  url: https://ibm-cloud-architecture.github.io/cloudnative-learning-101/
  start_page: cloudnative-learning-101::index.adoc

content:
  sources:
    - url: https://github.com/ibm-cloud-architecture/cloudnative-learning-101.git
      branches: 'master'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./supplemental-ui
output:
  dir: ./gh-pages
