apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: java-test
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: maven-image
        type: string
        default: maven:3.3-jdk-8
  steps:
    - name: test
      image: $(inputs.params.maven-image)
      workingdir: $(inputs.resources.source.path)
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          mvn test
          echo "tests passed with rc=$?"
      volumeMounts:
        - name: m2-repository
          mountPath: /.m2
  volumes:
    - name: m2-repository
      emptyDir: {}
