= Lab 2 - Docker
Hemankita Perabathini <Hemankita.Perabathini@ibm.com>
v1.0, 2019-05-28
:toc:
:imagesdir: images

== Introduction

In this lab, you will learn about how to use docker and how to run applications using docker.

== Prerequisites

- You need https://www.java.com/en/[Java] installed on your environment. You can download it https://www.java.com/download/[here]. Please install the latest version which is Java Version 8. Make sure you set `JAVA_HOME` environment variable. You can verify the version after installation using `java -version`.
- Create a https://hub.docker.com/[DockerHub account]. This account is needed to push images to docker registry. Also create a repository following the instructions https://docs.docker.com/docker-hub/repos/[here].
- You need to install https://www.docker.com/[Docker] in your environment. Follow the instructions https://docs.docker.com/docker-for-mac/install/[here] to install it on Mac and https://docs.docker.com/docker-for-windows/install/[here] to install it on Windows.

== Working with docker

Before proceeding, make sure docker is properly installed on your system. To verify this, run the below command.

[source, bash]
----
$ docker -v
----

If it is installed, you will see a version number something similar to below.

[source, bash]
----
Docker version 19.03.0-beta3, build c55e026
----

[big maroon]*Running a hello-world container*

Let us start with a `hello-world` container. To run a `hello-world` container, use the below command.

[source, bash]
----
$ docker run hello-world
----

If it is successfully run, you will see something like below.

[source, bash]
----
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
1b930d010525: Pull complete
Digest: sha256:41a65640635299bab090f783209c1e3a3f11934cf7756b09cb2f1e02147c6ed8
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
----

Since, `hello-world` image is not existing locally, it is pulled from `library/hello-world`. But if it is already existing, docker will not pull it every time but rather use the existing one.

This image is pulled from https://hub.docker.com/_/hello-world. Docker hub is a repository used to store docker images. Similarly, you can use your own registries to store images. For example, IBM Cloud provides you a container registry.

[big maroon]*Verifying the hello-world image*

To verify if an image is existing in your system locally, run the below command.

[source, bash]
----
$ docker images
----

You will then see something like below.

[source, bash]
----
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
hello-world         latest              fce289e99eb9        5 months ago        1.84kB
----

== Get the sample application

To get the sample application, you will need to clone it from github.

[source, bash]
----
# Clone the sample app
$ git clone https://github.com/ibm-cloud-architecture/cloudnative_sample_app.git

# Go to the project's root folder
$ cd cloudnative_sample_app/
----

== Run the application on Docker

=== Build the application

To build the application, use the below command.

[source, bash]
----
$ ./mvnw install
----

You will notice something at the end like below once done.

[source, bash]
----
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ cloudnativesampleapp ---
[INFO] Installing /Users/user@ibm.com/cloudnative_sample_app/target/cloudnativesampleapp-1.0-SNAPSHOT.jar to /Users/user@ibm.com/.m2/repository/projects/cloudnativesampleapp/1.0-SNAPSHOT/cloudnativesampleapp-1.0-SNAPSHOT.jar
[INFO] Installing /Users/user@ibm.com/cloudnative_sample_app/pom.xml to /Users/user@ibm.com/.m2/repository/projects/cloudnativesampleapp/1.0-SNAPSHOT/cloudnativesampleapp-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34.714 s
[INFO] Finished at: 2019-06-28T11:11:06-05:00
[INFO] ------------------------------------------------------------------------
----

=== Build the docker image

Let's take look at the docker file before building it.

----
FROM openliberty/open-liberty:springBoot2-ubi-min as staging
USER root
COPY target/cloudnativesampleapp-1.0-SNAPSHOT.jar /staging/fatClinic.jar

RUN springBootUtility thin \
 --sourceAppPath=/staging/fatClinic.jar \
 --targetThinAppPath=/staging/thinClinic.jar \
 --targetLibCachePath=/staging/lib.index.cache

FROM openliberty/open-liberty:springBoot2-ubi-min
USER root
COPY --from=staging /staging/lib.index.cache /opt/ol/wlp/usr/shared/resources/lib.index.cache
COPY --from=staging /staging/thinClinic.jar /config/dropins/spring/thinClinic.jar

RUN chown -R 1001.0 /config && chmod -R g+rw /config
RUN chown -R 1001.0 /opt/ol/wlp/usr/shared/resources/lib.index.cache && chmod -R g+rw /opt/ol/wlp/usr/shared/resources/lib.index.cache

USER 1001
----

- Using the `FROM` instruction, we provide the name and tag of an image that should be used as our base. This must always be the first instruction in the Dockerfile.
- `USER` instruction sets the username (or UID).
- Using `COPY` instruction, we copy new contents from the source filesystem to the container filesystem.
- `RUN` instruction executes the commands.

Once, you have the docker file ready, the next step is to build it. The `build` command allows you to build a docker image which you can later run as a container.

The command is as follows.

[source, bash]
----
$ docker build -t <image_name>:<image_tag> .
----

Here, `-t` flag allows you to add a name to your image and optionally you can also add a tag. If you don't add a tag, by default the tag is `latest`. Also, the `.` at the end of the command specifies that the path for the Dockerfile is the current directory.

To build the docker image for our sample application, run the below command.

[source, bash]
----
$ docker build -t greeting:v1.0.0 .
----

You will see something like below.

[source, bash]
----
$ docker build -t greeting:v1.0.0 .
Sending build context to Docker daemon  22.17MB
Step 1/11 : FROM openliberty/open-liberty:springBoot2-ubi-min as staging
springBoot2-ubi-min: Pulling from openliberty/open-liberty
949de0c45264: Pull complete
7e9d54341c0e: Pull complete
32db7409eb5f: Pull complete
7640ec54eca1: Pull complete
f081c7c2f0e0: Pull complete
51c03cd5ee07: Pull complete
f716fe3cdacf: Pull complete
daed7a0739aa: Pull complete
d876e280fa2d: Pull complete
Digest: sha256:d51b2eb61d32599712c333f8d6a4e4297cb57d6c7981ab15a14f744d46710b0f
Status: Downloaded newer image for openliberty/open-liberty:springBoot2-ubi-min
 ---> bcfcb2c5ce16
Step 2/11 : USER root
 ---> Running in 26a12ce640db
Removing intermediate container 26a12ce640db
 ---> 9e891aecf123
Step 3/11 : COPY target/cloudnativesampleapp-1.0-SNAPSHOT.jar /staging/fatClinic.jar
 ---> 7c0f26bc76e7
Step 4/11 : RUN springBootUtility thin  --sourceAppPath=/staging/fatClinic.jar  --targetThinAppPath=/staging/thinClinic.jar  --targetLibCachePath=/staging/lib.index.cache
 ---> Running in 2d68ff957a28
Creating a thin application from: /staging/fatClinic.jar
Library cache: /staging/lib.index.cache
Thin application: /staging/thinClinic.jar
Removing intermediate container 2d68ff957a28
 ---> f9cad508cb4c
Step 5/11 : FROM openliberty/open-liberty:springBoot2-ubi-min
 ---> bcfcb2c5ce16
Step 6/11 : USER root
 ---> Using cache
 ---> 9e891aecf123
Step 7/11 : COPY --from=staging /staging/lib.index.cache /opt/ol/wlp/usr/shared/resources/lib.index.cache
 ---> 0e27922ad7a6
Step 8/11 : COPY --from=staging /staging/thinClinic.jar /config/dropins/spring/thinClinic.jar
 ---> 93bd8360110b
Step 9/11 : RUN chown -R 1001.0 /config && chmod -R g+rw /config
 ---> Running in ea42c7b6f92a
Removing intermediate container ea42c7b6f92a
 ---> 764ef4196d1b
Step 10/11 : RUN chown -R 1001.0 /opt/ol/wlp/usr/shared/resources/lib.index.cache && chmod -R g+rw /opt/ol/wlp/usr/shared/resources/lib.index.cache
 ---> Running in 2b1738422b89
Removing intermediate container 2b1738422b89
 ---> af170c7af294
Step 11/11 : USER 1001
 ---> Running in 98fc928c9778
Removing intermediate container 98fc928c9778
 ---> 89bd7032fdee
Successfully built 89bd7032fdee
Successfully tagged greeting:v1.0.0
----

To verify if the image is built successfully, run the below command.

[source, bash]
----
$ docker images
----

It shows the images, their repository and tags, and their size.

The output will be as follows.

[source, bash]
----
$ docker images
REPOSITORY                           TAG                   IMAGE ID            CREATED             SIZE
greeting                             v1.0.0                89bd7032fdee        51 seconds ago      402MB
openliberty/open-liberty             springBoot2-ubi-min   bcfcb2c5ce16        6 days ago          366MB
hello-world                          latest                f9cad508cb4c        5 months ago        1.84kB
----

=== Run the docker container

- To run the docker container, use the below command.

[source, bash]
----
$ docker run -p <port_to_expose>:<port> -d --name <container_name> <image_name>:<tag>
----

- `-p`: Allows you to publish the containers port to the host.
- `-d`: Runs the container in background in detached mode.
- `--name`: Allows you to specify the name of the container. If you don't use this one, docker creates a name automatically.

To run the docker container for our sample application, use the below command.

[source, bash]
----
$ docker run -p 9080:9080 -d --name greeting greeting:v1.0.0
----

Once done, you will have something like below.

[source, bash]
----
$ docker run -p 9080:9080 -d --name greeting greeting:v1.0.0
bc2dc95a6bd1f51a226b291999da9031f4443096c1462cb3fead3df36613b753
----

Also, docker cannot create two containers with the same name. If you try to run the same container having the same name again, you will see something like below.

[source, bash]
----
$ docker run -p 9080:9080 -d --name greeting greeting:v1.0.0
docker: Error response from daemon: Conflict. The container name "/greeting" is already in use by container "a74b91789b29af6e7be92b30d0e68eef852bfb24336a44ef1485bb58becbd664". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
----

It is a good practice to name your containers. Naming helps you to discover your service easily.

- To list all the running containers, use the below command.

[source, bash]
----
$ docker ps
----

You will see something like below.

[source, bash]
----
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
bc2dc95a6bd1        greeting:v1.0.0     "/opt/ol/helpers/run…"   18 minutes ago      Up 18 minutes       0.0.0.0:9080->9080/tcp, 9443/tcp   greeting
----

- To know more about the container, you can inspect the container.

Run the below command.

[source, bash]
----
$ docker inspect <container-name|container-id>
----

By inspecting the container, you can access detailed information about the container. By using this command, you get to know the details about network settings, volumes, configs, state etc.

If we consider our container, it is as follows. You can see lot of information about the `greeting` container.

[source, bash]
----
$ docker inspect greeting
[
    {
        "Id": "bc2dc95a6bd1f51a226b291999da9031f4443096c1462cb3fead3df36613b753",
        "Created": "2019-08-30T16:56:40.2081539Z",
        "Path": "/opt/ol/helpers/runtime/docker-server.sh",
        "Args": [
            "/opt/ol/wlp/bin/server",
            "run",
            "defaultServer"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 27548,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-08-30T16:56:41.0927889Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        ..........
        ..........
        ..........
    }
]
----

- To get the logs, you use the below command.

[source, bash]
----
$ docker logs <container-name|container-id>
----

It helps you to access the logs of your container. It allows you to debug the container if it fails. It also lets you to know what is happening with your application.

If we consider our container, it is as follows.

[source, bash]
----
$ docker logs greeting
----

At the end, you will see something like below.

[source, bash]
----
.   ____          _            __ _ _
/\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
\\/  ___)| |_)| | | | | || (_| |  ) ) ) )
'  |____| .__|_| |_|_| |_\__, | / / / /
=========|_|==============|___/=/_/_/_/
:: Spring Boot ::        (v2.1.7.RELEASE)
2019-08-30 16:57:01.494  INFO 1 --- [ecutor-thread-5] application.SBApplication                : Starting SBApplication on bc2dc95a6bd1 with PID 1 (/opt/ol/wlp/usr/servers/defaultServer/dropins/spring/thinClinic.jar started by default in /opt/ol/wlp/output/defaultServer)
2019-08-30 16:57:01.601  INFO 1 --- [ecutor-thread-5] application.SBApplication                : No active profile set, falling back to default profiles: default
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://bc2dc95a6bd1:9080/
2019-08-30 16:57:09.641  INFO 1 --- [cutor-thread-25] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 7672 ms
2019-08-30 16:57:12.279  INFO 1 --- [ecutor-thread-5] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 15 endpoint(s) beneath base path '/actuator'
2019-08-30 16:57:12.974  INFO 1 --- [ecutor-thread-5] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-08-30 16:57:13.860  INFO 1 --- [ecutor-thread-5] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2019-08-30 16:57:13.961  INFO 1 --- [ecutor-thread-5] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2019-08-30 16:57:14.020  INFO 1 --- [ecutor-thread-5] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2019-08-30 16:57:14.504  INFO 1 --- [ecutor-thread-5] application.SBApplication                : Started SBApplication in 17.584 seconds (JVM running for 33.368)
[AUDIT   ] CWWKZ0001I: Application thinClinic started in 21.090 seconds.
[AUDIT   ] CWWKF0012I: The server installed the following features: [el-3.0, jsp-2.3, servlet-4.0, springBoot-2.0, ssl-1.0, transportSecurity-1.0, websocket-1.1].
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 33.103 seconds.
----

This shows that the Spring Boot application is successfully started.

=== Access the application

- To access the application, open the browser and access http://localhost:9080/greeting?name=John.

You will see something like below.

[source, bash]
----
{"id":2,"content":"Welcome to Cloudnative bootcamp !!! Hello, John :)"}
----

[maroon]*Container Image Registry*

Container Image Registry is a place where you can store the container images. They can be public or private registries. They can be hosted by third party as well. In this lab, we are using DockerHub.

=== Pushing an image to a Registry

Let us now push the image to docker hub registry.

- Before pushing the image to the registry, one needs to login. Let us now login into the docker hub registry.

[source, bash]
----
$ docker login
----

Enter your Docker Hub credentials.

[source, bash]
----
$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: <user_name>
Password:
Login Succeeded
----

- Tag your image. To push an image to a registry, you need to tag it with the repository name and port (port is optional). This command helps you to do that.

[source, bash]
----
$ docker tag <src_image_name>:<tag> <repository_name>/<target_image>:<tag>
----

Let us now tag the image we built previously.

[source, bash]
----
$ docker tag greeting:v1.0.0 <repository_name>/greeting:v1.0.0
----

- Now push the image to the registry. This allows you to share images to a registry.

[source, bash]
----
$ docker push <repository_name>/<image_name>:<tag>
----

In our case, it will be as follows.

[source, bash]
----
$ docker push <repository_name>/greeting:v1.0.0
----

If everything goes fine, you will see something like below.

[source, bash]
----
$ docker push <repository_name>/greeting:v1.0.0
The push refers to repository [docker.io/<repository_name>/greeting]
2e4d09cd03a2: Pushed
d862b7819235: Pushed
a9212239031e: Pushed
4be784548734: Pushed
a43c287826a1: Mounted from library/ibmjava
e936f9f1df3e: Mounted from library/ibmjava
92d3f22d44f3: Mounted from library/ibmjava
10e46f329a25: Mounted from library/ibmjava
24ab7de5faec: Mounted from library/ibmjava
1ea5a27b0484: Mounted from library/ibmjava
v1.0.0: digest: sha256:21c2034646a31a18b053546df00d9ce2e0871bafcdf764f872a318a54562e6b4 size: 2415
----

Once the push is successful, your image will be residing in the registry.

=== Clean Up

- To stop the container, run the below command.

[source, bash]
----
$ docker stop <container-name|container-id>
----

For our sample application, it is as follows.

[source, bash]
----
$ docker stop greeting
greeting
----

- To remove the container, run the below command.

[source, bash]
----
$ docker rm <container-name|container-id>
----

For our sample application, it is as follows.

[source, bash]
----
$ docker rm greeting
greeting
----

- To remove the image, run the below command.

[source, bash]
----
$ docker rmi <image_id>
----

Get the image_ids and then remove them. Use the below commands to do that.

[source, bash]
----
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
greeting            v1.0.0              3ae7dfc4b794        About an hour ago   251MB
ibmjava             8-sfj               ab418b419902        9 days ago          222MB

$ docker rmi 3ae7dfc4b794 ab418b419902
Untagged: greeting:v1.0.0
Deleted: sha256:3ae7dfc4b794bf97684110e0a9392b121f63002ab35a46facf3edf281f47d27a
Deleted: sha256:3200b25a9898291bdee9e46c9fff1214791858bfc789e5ee9d6f1455fc9d33c6
Deleted: sha256:ad42c72c8e8a52d8730aeb21e28ca408951302c61a762c89fcbf502b143777ce
Deleted: sha256:393041ba04b55817a106508daa2afdffc9b011b550ed684c9b6a42c070487090
Deleted: sha256:d0693367c12ce7d34415ffce10e489a6fd9c8a3cd8c2c944df1374969b60835e
Untagged: ibmjava:8-sfj
Untagged: ibmjava@sha256:aaef6e7d14b3c63b8df9eaea45334d3cc7678ba3878dfcb630be8706719df97e
Deleted: sha256:ab418b419902ecc54a6f2b4c0f485c1105eec3395f253040087a954528de7b1b
Deleted: sha256:2ffcfbe8352bdf9c70b66692e436ab03f01ca3dce37d7d49c79f5c4c80ec2044
Deleted: sha256:c896bc720df99ee1a6ce305d17edfda42b043a47223ff2ac3e4f94199e6d595b
Deleted: sha256:03952d61b1fc131f23629c02f7ffb93708ae77108a32e4eedd83d4ec987ba51c
Deleted: sha256:a48e1b8909b41276ed1666d5262d981258163c6f0998b58e61efa4188944652e
Deleted: sha256:872ef8aee8632246e43a346a70274030c3613fe81af162a2fb6d14e1fcba980d
Deleted: sha256:1ea5a27b0484f2a227275fbb913d281461d9f356134a56002574904c3cfdea04
----

=== Pulling an image from the registry

Sometimes, you may need the images that are residing on your registry. Or you may want to use some public images out there. Then, we need to pull the image from the registry.

To pull the image from the registry, use the below command.

[source, bash]
----
$ docker pull <repository_name>/<image_name>:<tag>
----

Since, we deleted the one we created previously, let us now push it from the registry.

[source, bash]
----
$ docker pull <repository_name>/greeting:v1.0.0
----

If it successfully got pulled, we will see something like below.

[source, bash]
----
ddcb5f219ce2: Pull complete
e3371bbd24a0: Pull complete
49d2efb3c01b: Pull complete
Digest: sha256:21c2034646a31a18b053546df00d9ce2e0871bafcdf764f872a318a54562e6b4
Status: Downloaded newer image for <repository_name>/greeting:v1.0.0
docker.io/<repository_name>/greeting:v1.0.0
----

== Run the application on Docker using multi-stage build

In this, building the application is a part of the docker image. It automatically does it for you. You need not run `mvn install` explicitly.

=== Build the docker image

Let's take look at the docker file before building it.

----
# Build stage - could use maven or our image
FROM maven:3.3-jdk-8 as builder

# Creating Work directory
ENV BUILD_DIR=/usr/src/app/
RUN mkdir $BUILD_DIR
WORKDIR $BUILD_DIR

# Reuse local .m2. if not all the dependencies will be always downloaded
# This can be removed if you want to
VOLUME ${HOME}/.m2:/root/.m2
ADD . /usr/src/app

RUN bash -c " mvn clean install"

FROM openliberty/open-liberty:springBoot2-ubi-min as staging
USER root

# Create app directory
ENV APP_HOME=/app
WORKDIR $APP_HOME

# Copy jar file over from builder stage
COPY --from=builder /usr/src/app/target/cloudnativesampleapp-1.0-SNAPSHOT.jar $APP_HOME
RUN mv ./cloudnativesampleapp-1.0-SNAPSHOT.jar app.jar

RUN springBootUtility thin \
 --sourceAppPath=app.jar \
 --targetThinAppPath=/staging/thinClinic.jar \
 --targetLibCachePath=/staging/lib.index.cache

FROM openliberty/open-liberty:springBoot2-ubi-min
USER root
COPY --from=staging /staging/lib.index.cache /opt/ol/wlp/usr/shared/resources/lib.index.cache
COPY --from=staging /staging/thinClinic.jar /config/dropins/spring/thinClinic.jar

RUN chown -R 1001.0 /config && chmod -R g+rw /config
RUN chown -R 1001.0 /opt/ol/wlp/usr/shared/resources/lib.index.cache && chmod -R g+rw /opt/ol/wlp/usr/shared/resources/lib.index.cache

USER 1001
----

This Dockerfile leverages multi-stage builds, which lets you create multiple stages in your Dockerfile to do certain tasks.

In our case, we have two stages.

- The first one uses `maven:3.3-jdk-8` as its base image to download and build the project and its dependencies using Maven.
- The second stage uses `openliberty/open-liberty:springBoot2-ubi-min` as its base image to run the compiled code from the previous stage.

The advantage of using the multi-stage builds approach is that the resulting image only uses the base image of the last stage. Meaning that in our case, we will only end up with the `openliberty/open-liberty:springBoot2-ubi-min` as our base image, which is much tinier than having an image that has both Maven and the JRE.

By using the multi-stage builds approach when it makes sense to use it, you will end up with much lighter and easier to maintain images, which can save you space on your Docker Registry. Also, having tinier images usually means less resource consumption on your worker nodes, which can result cost-savings.

To build the docker image, run the below command.

[source, bash]
----
$ docker build -f Dockerfile.multistage -t greeting:v2.0.0 .
----

You will see something like below.

[source, bash]
----
$ docker build -f Dockerfile.multistage -t greeting:v2.0.0 .
Sending build context to Docker daemon  22.17MB
Step 1/21 : FROM maven:3.3-jdk-8 as builder
3.3-jdk-8: Pulling from library/maven
6d827a3ef358: Pull complete
2726297beaf1: Pull complete
7d27bd3d7fec: Pull complete
e61641c845ed: Pull complete
cce4cca5b76b: Pull complete
6826227500b0: Pull complete
c03b117ffd91: Pull complete
821a1547b435: Pull complete
2bd47f6b1b42: Pull complete
e4cf3e9f705c: Pull complete
3733107c5c01: Pull complete
Digest: sha256:18e8bd367c73c93e29d62571ee235e106b18bf6718aeb235c7a07840328bba71
Status: Downloaded newer image for maven:3.3-jdk-8
 ---> 9997d8483b2f
Step 2/21 : ENV BUILD_DIR=/usr/src/app/
 ---> Running in 02c2c0bdb8bf
Removing intermediate container 02c2c0bdb8bf
 ---> f09a7e2e03e7
Step 3/21 : RUN mkdir $BUILD_DIR
 ---> Running in af3141c3e1fc
Removing intermediate container af3141c3e1fc
 ---> 98aee6a73219
Step 4/21 : WORKDIR $BUILD_DIR
 ---> Running in e85580f76678
Removing intermediate container e85580f76678
 ---> e4bb0b1b310d
Step 5/21 : VOLUME ${HOME}/.m2:/root/.m2
 ---> Running in bec55df2bd55
Removing intermediate container bec55df2bd55
 ---> 71d3ddd3775b
Step 6/21 : ADD . /usr/src/app
 ---> 3a7a1f086e77
Step 7/21 : RUN bash -c " mvn clean install"
 ---> Running in 8c726a5c1380
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.1.7.RELEASE/spring-boot-starter-parent-2.1.7.RELEASE.pom
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.1.7.RELEASE/spring-boot-starter-parent-2.1.7.RELEASE.pom (10 KB at 10.4 KB/sec)
.................
.................
.................
Step 20/21 : RUN chown -R 1001.0 /opt/ol/wlp/usr/shared/resources/lib.index.cache && chmod -R g+rw /opt/ol/wlp/usr/shared/resources/lib.index.cache
 ---> Running in ae77279b238c
Removing intermediate container ae77279b238c
 ---> 74640a653475
Step 21/21 : USER 1001
 ---> Running in 01c24024899a
Removing intermediate container 01c24024899a
 ---> 55240d6d8edc
Successfully built 55240d6d8edc
Successfully tagged greeting:v2.0.0
----

To verify if the image is built successfully, run the below command.

[source, bash]
----
$ docker images
----

You will have something as follows.

[source, bash]
----
$ docker images
REPOSITORY                           TAG                   IMAGE ID            CREATED              SIZE
greeting                             v2.0.0                55240d6d8edc        45 seconds ago       402MB
openliberty/open-liberty             springBoot2-ubi-min   bcfcb2c5ce16        6 days ago           366MB
maven                                3.3-jdk-8             9997d8483b2f        2 years ago          653MB
----

=== Run the docker container

- To run the docker container, use the below command.

[source, bash]
----
$ docker run -p 9080:9080 -d --name greeting_multistage greeting:v2.0.0
----

Once done, you will have something like below.

[source, bash]
----
$ docker run -p 9080:9080 -d --name greeting_multistage greeting:v2.0.0
baf6f41b3ab785dfdccd9d83486b351a9d9718fcc3690f68e9f574e36c914844
----

- To list all the running containers, use the below command.

[source, bash]
----
$ docker ps
----

You will have something like below.

[source, bash]
----
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
baf6f41b3ab7        greeting:v2.0.0     "/opt/ol/helpers/run…"   26 seconds ago      Up 25 seconds       0.0.0.0:9080->9080/tcp, 9443/tcp   greeting_multistage
----

- To know more about the container, you can inspect the container.

Run the below command.

[source, bash]
----
$ docker inspect <container-name|container-id>
----

If we consider our container, it is as follows.

[source, bash]
----
$ docker inspect greeting_multistage
----

- To get the logs, you use the below command.

[source, bash]
----
$ docker logs <container-name|container-id>
----

If we consider our container, it is as follows.

[source, bash]
----
$ docker logs greeting_multistage
----

=== Access the application

- To access the application, open the browser and access http://localhost:9080/greeting?name=John.

You will see something like below.

[source, bash]
----
{"id":2,"content":"Welcome to Cloudnative bootcamp !!! Hello, John :)"}
----

=== Clean Up

- To stop the container, run the below command.

[source, bash]
----
$ docker stop <container-name|container-id>
----

For our sample application, it is as follows.

[source, bash]
----
$ docker stop greeting_multistage
greeting_multistage
----

- To remove the container, run the below command.

[source, bash]
----
$ docker rm <container-name|container-id>
----

For our sample application, it is as follows.

[source, bash]
----
$ docker rm greeting_multistage
greeting_multistage
----

- To remove the image, run the below command.

[source, bash]
----
$ docker rmi <image_id>
----

Get the image_ids and then remove them. Use the below commands to do that.

[source, bash]
----
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
greeting            v2.0.0              f79f112b85de        5 minutes ago       317MB
ibmjava             8-sfj               ab418b419902        9 days ago          222MB
maven               3.3-jdk-8           9997d8483b2f        2 years ago         653MB

$ docker rmi f79f112b85de ab418b419902 9997d8483b2f
Untagged: greeting:v2.0.0
Deleted: sha256:f79f112b85de5ecfd0bda14e513c46fe6ca97d7a482b558125a2ae6e746f4fa8
Deleted: sha256:78b047c21b2efe3b407dfa94274dfab63711a21ab17361e4ef2045bac2cdb510
Deleted: sha256:62d507c2ca92e54550759715e481588568461393d300e1e17a1cccb0ef42c65a
Deleted: sha256:adc85f6f75dc02ec2df1f693392656d07ab6d6e1d8afe5c25faf4ab4c514dee7
Deleted: sha256:ac671642300875b39c4fdc7ce4de82a7d1367f946644b13573f1ae31c490a12e
Deleted: sha256:39221665a68e2890f4c3dba1cc977e16340f8e328be2697b1b89a6a2b8e9c246
Deleted: sha256:c2c568f2599e5b74f79cbe2ebfbdf1c970ee6c3848e52494094b0e2d5632a40f
Deleted: sha256:320f2d955769604fefff9ab673f2e4c4815e050f8eff51f83351df3691f373f5
Deleted: sha256:64bc278ff6faceaf74159a463525d4dfe523392308a5a6d735e4e626a16885a7
Deleted: sha256:1482dbbeb1629cd9b729092d25d0b666a739c53fe1531f74635179f77ba1ac93
Deleted: sha256:c3cdbce0b6e8a74ea8cb81dc2a91cb399d64eb75558c3a2ace825a7b3999e042
Untagged: ibmjava:8-sfj
Untagged: ibmjava@sha256:aaef6e7d14b3c63b8df9eaea45334d3cc7678ba3878dfcb630be8706719df97e
Deleted: sha256:ab418b419902ecc54a6f2b4c0f485c1105eec3395f253040087a954528de7b1b
Deleted: sha256:2ffcfbe8352bdf9c70b66692e436ab03f01ca3dce37d7d49c79f5c4c80ec2044
Deleted: sha256:c896bc720df99ee1a6ce305d17edfda42b043a47223ff2ac3e4f94199e6d595b
Deleted: sha256:03952d61b1fc131f23629c02f7ffb93708ae77108a32e4eedd83d4ec987ba51c
Deleted: sha256:a48e1b8909b41276ed1666d5262d981258163c6f0998b58e61efa4188944652e
Deleted: sha256:872ef8aee8632246e43a346a70274030c3613fe81af162a2fb6d14e1fcba980d
Deleted: sha256:1ea5a27b0484f2a227275fbb913d281461d9f356134a56002574904c3cfdea04
Untagged: maven:3.3-jdk-8
Untagged: maven@sha256:18e8bd367c73c93e29d62571ee235e106b18bf6718aeb235c7a07840328bba71
Deleted: sha256:9997d8483b2fc521a4159feab922546dda0c5c22b5084f86dfab48f123ae4364
Deleted: sha256:4670a3a3ccbe1fa08dbcd29629e833086949809a5bf6fe1ac4e336b65f0c814c
Deleted: sha256:4501fab525c27427b85718fc477889071ec8a7adf2c3629bcff4246e4d1df787
Deleted: sha256:32babe003c3a531aebcdb501deb957c9933f7c90beabfab5d8805f62a084f398
Deleted: sha256:7d628fad6450f42db382a12b2d5470166b63fce76f6b1865f39718ad99accfab
Deleted: sha256:6bc44dc0c6c47463f610e82d75246a0f804c27f86bdf46a8ae1563bb3cc77142
Deleted: sha256:73d13c48b7fe3dbbf513351da9e439a2f38332c4cfcc149c6e7368dafc31e2d9
Deleted: sha256:dcd168f76c182f075b2dcdafe6a80dcb6fa4180588214df23322b706dc2b9536
Deleted: sha256:33690a5a483b7684bc809f4c4d8992d946f063b23fc99f68e661383953d910a8
Deleted: sha256:2ecb867048da2f6e2740814c177ca71c959ab2c91acaefbe827149302b20076f
Deleted: sha256:763ac6a64f068afd061160ff77b7ab41f61aba49b554bfe39ca033fcbf4f2d3c
Deleted: sha256:5d6cbe0dbcf9a675e86aa0fbedf7ed8756d557c7468d6a7c64bde7fa9e029636
----

== Conclusion

You have successfully completed this lab! Let's take a look at what you learned and did today:

- Learned about Dockerfile.
- Learned about docker images.
- Learned about docker containers.
- Learned about multi-stage docker builds.
- Ran the Greetings service on Docker.

Congratulations !!!
