:imagesdir: ../images
= Kubernetes Deployments
video::Sulw5ndbE88[youtube,width=700,height=500]

== Pods

A Pod is the basic execution unit of a Kubernetes application–the smallest and simplest unit in the Kubernetes object model that you create or deploy. A Pod represents processes running on your cluster. Pods can run a single container or multiple containers at one time. 

.Read More
NOTE: Pod Information Overview: 
      https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/[Here , window="_blank"]


=== ReplicaSets

A ReplicaSet is a defined set of fields that declares the number of replicas needed to obtain the desired state. A ReplicaSet fulfills it's purpose by creating and deleting Pods to match the desired number defined.  When a ReplicaSet creates a pod it uses a Pod Template. A ReplicaSet ensured the proper number of replicated pods are running at any given time, but it is recommended to use Deployments instead of directly using ReplicaSets since they are a higher level concept that manages ReplicaSets.

.Check it out
NOTE: ReplicaSet Example: 
      https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#example[Example , window="_blank"]

== Deployments

A kubernetes deployment describes the desired state for a kubernetes cluster. The deployment controller changes the actual state to meet the desired state at a controlled rate.  Changes to a deployment can lead to new ReplicaSets, removal of previous deployments and allocate the resources for the new deployment.  Deployments can be updated and rolled back in case of any errors or mistakes made when editing a deployment.  A deployment can also be replicated in order to scale any deployment. In the link below you will find an example of a deployment. Below the example is also more information on updating, scaling, and pausing deployments.

.Check it out
NOTE: Deployment Example: 
      https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment[Example , window="_blank"]

== Try It Out

The link below will take you to Katacoda to walk you through creating a deployment and service via a YAML file. You will also change the number of replicas for the deployment and see how it automatically deploys the replicas for you. 

.Walkthrough
NOTE: Deployments using YAML: 
      https://www.katacoda.com/courses/kubernetes/creating-kubernetes-yaml-definitions/[Katacoda , window="_blank"]
